account:
  enabled: true
binding:
  enabled: true
clusterRole:
  enabled: true
  rules:
  - apiGroups:
    - ''
    resources:
    - nodes
    - services
    verbs:
    - get
    - list
  - apiGroups:
    - batch
    resources:
    - cronjobs
    verbs:
    - patch
