statefulset:
  enabled: true
  image: me-west1-docker.pkg.dev/minereye-delivery-public/minereye-services/ann-service:v3.6.2
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    name: regcred
  ports:
  - containerPort: 2400
    name: python-port
  replicas: 1
  resources:
    requests:
      memory: 100Mi
  securityContext:
    runAsUser: 1001
  volume:
    mode:
    - ReadWriteOnce
    mountPath: /data
    size: 40Gi
svc:
  enabled: true
  ports:
  - port: 2400
    protocol: TCP
    targetPort: 2400
