{
 "title": "CPU Utilization Details (Cores) Enway",
 "description": "This is an dashboard for which provides CPU utilization details for multi-core systems.  It allows to easily see if overall CPU usage is high or if there are overloaded cores. Designed to be used with node-exporter >=0.16.0, as node_cpu is now renamed to node_cpu_seconds_total. forked from percona",
 "tags": [
  "Enway",
  "CPU"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu_seconds_total\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu_seconds_total{instance=\"$host\"}, cpu)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$host - Current CPU Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Overall CPU Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "CPU Cores Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Core CPU Usage",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
    }
   ]
  },
  { "title": "Per Core Usage Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  }
 ]
}
{
 "title": "Tracker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "General Syslog Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "syslog_general_total" }
   ]
  },
  {
   "title": "General Syslog Events / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(syslog_general_total[5m])" }
   ]
  },
  {
   "title": "Connector Syslog Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "syslog_connector_total" }
   ]
  },
  {
   "title": "Connector Syslog Events / Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(syslog_connector_total[5m])"
    }
   ]
  }
 ]
}
{
 "title": "Engine",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Batch Iteration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "en_batch_iter_total" }
   ]
  },
  {
   "title": "Batch Iteration / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(en_batch_iter_total[5m])" }
   ]
  },
  {
   "title": "Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "en_work_q" }
   ]
  },
  {
   "title": "Process Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(en_process_time_bucket[10m])) by (le)"
    }
   ]
  },
  {
   "title": "Batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "en_batch_scan_total" },
    { "expr": "en_batch_events_total" },
    { "expr": "en_batch_entity_total" }
   ]
  },
  {
   "title": "Batches / Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(en_batch_scan_total[5m]) * 60"
    },
    {
     "expr": "rate(en_batch_events_total[5m]) * 60"
    },
    {
     "expr": "rate(en_batch_entity_total[5m]) * 60"
    }
   ]
  },
  {
   "title": "Process File / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(en_processf_file_total[5m])"
    }
   ]
  },
  {
   "title": "Entities SHA1 / Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(en_enregression_sha1_total[5m])"
    }
   ]
  }
 ]
}
{
 "title": "Upload / Download files",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Productivity rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_files" },
    { "expr": "download_rate" },
    { "expr": "risk_analyzer_rate" },
    { "expr": "pandas_rate" },
    { "expr": "nlp_rate" },
    { "expr": "lda_rate" },
    { "expr": "text_entities_rate" },
    { "expr": "ocr_rate" },
    { "expr": "mip_rate" },
    { "expr": "html_extractor_rate" },
    { "expr": "router_rate" },
    { "expr": "seclore_rate" },
    { "expr": "signal_rate" },
    { "expr": "tika_rate" },
    { "expr": "zip_extractor_rate" },
    {}
   ]
  },
  {
   "title": "Pods get / finish",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "FileType_get" },
    { "expr": "FileType_finish" },
    { "expr": "SecloreDecrypt_get" },
    { "expr": "SecloreDecrypt_finish" },
    { "expr": "MipDecrypt_get " },
    { "expr": "MipDecrypt_finish" },
    { "expr": "SignalExtractor_get " },
    { "expr": "SignalExtractor_finish" },
    { "expr": "PandasQueue_get " },
    { "expr": "PandasQueue_finish" },
    { "expr": "ZipExtractor_get " },
    { "expr": "ZipExtractor_finish" },
    { "expr": "OcrExtractor_get" },
    { "expr": "OcrExtractor_finish" },
    { "expr": "TikaExtractor_get" },
    { "expr": "TikaExtractor_finish" },
    { "expr": "HtmlExtractor_get" },
    { "expr": "HtmlExtractor_finish" },
    { "expr": "LdaQueue_get" },
    { "expr": "LdaQueue_finish" },
    { "expr": "TextEntitiesQueue_get" },
    { "expr": "TextEntitiesQueue_finish" },
    { "expr": "RiskAnalyzer_get" },
    { "expr": "RiskAnalyzer_finish" },
    { "expr": "NlpQueue_get" },
    { "expr": "NlpQueue_finish" }
   ]
  },
  {
   "title": "Queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_files" },
    { "expr": "tika_q_len" },
    { "expr": "signal_q_len" },
    { "expr": "nlp_q_len" },
    { "expr": "text-entities_q_len" },
    { "expr": "lda_q_len" },
    { "expr": "risk-analyzer_q_len" },
    { "expr": "zip-extractor_q_len" },
    { "expr": "es-upload_q_len" },
    { "expr": "download_rate" },
    { "expr": "html-extractor_q_len" },
    { "expr": "router_q_len" }
   ]
  },
  {
   "title": "Upload / Download",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_files" },
    { "expr": "download_files" },
    { "expr": "files_in_pipe" }
   ]
  }
 ]
}
{
 "title": "Crawler",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Files Found",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_found_file" }
   ]
  },
  {
   "title": "Files Found / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(c_found_file[5m])" }
   ]
  },
  {
   "title": "New Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_found_new_file" }
   ]
  },
  {
   "title": "New Files / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(c_found_new_file[5m])" }
   ]
  },
  {
   "title": "Found Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_found_size" }
   ]
  },
  {
   "title": "To Download Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_to_download_q" }
   ]
  },
  {
   "title": "Downloaded Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_downloaded_file_total" }
   ]
  },
  {
   "title": "Download Files / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(c_downloaded_file_total[5m])"
    }
   ]
  },
  {
   "title": "Download MB Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dl_mb_rate" }
   ]
  },
  {
   "title": "To Process Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_to_process_q" }
   ]
  },
  {
   "title": "Downloaded Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "c_downloaded_size_total" }
   ]
  },
  {
   "title": "Download Size / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(c_downloaded_size_total[5m])"
    }
   ]
  }
 ]
}
{
 "title": "Entities Regression",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Text Batch Iter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "er_text_batch_iter_total" }
   ]
  },
  {
   "title": "Text Batch Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "er_text_batch_q" }
   ]
  },
  {
   "title": "Total Text Iterations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "er_text_iter_total" }
   ]
  }
 ]
}
{
 "title": "Hubble",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows processed Per Node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "min"
    },
    {
     "expr": "max(sum(rate(hubble_flows_processed_total[1m])) by (pod))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Flows Types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "L7 Flow Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"L7\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Trace Flow Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total{type=\"Trace\"}[1m])) by (pod, subtype)",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Forwarded vs Dropped",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_flows_processed_total[1m])) by (pod, verdict)",
     "legendFormat": "{{verdict}}"
    }
   ]
  },
  {
   "title": "Drop Reason",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Protocol Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(hubble_port_distribution_total[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Port Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum (rate(hubble_port_distribution_total{port!=\"0\"}[1m])) by (pod, port, protocol))",
     "legendFormat": "{{port}}/{{protocol}}"
    }
   ]
  },
  {
   "title": "TCPv4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv4 SYN-ACKs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv4\", flag=\"SYN-ACK\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "TCPv6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\"}[1m])) by (pod, flag)",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Missing TCPv6 SYN-ACKs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN\"}[1m])) by (pod) - sum(rate(hubble_tcp_flags_total{family=\"IPv6\", flag=\"SYN-ACK\"}[1m])) by (pod)",
     "legendFormat": "Missing SYN-ACK"
    }
   ]
  },
  {
   "title": "ICMPv4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv4 Echo-Reply",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoRequest\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv4\", type=\"EchoReply\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  {
   "title": "ICMPv6",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\"}[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Missing ICMPv6 Echo-Reply",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoRequest\"}[1m])) by (pod) - sum(rate(hubble_icmp_total{family=\"IPv6\", type=\"EchoReply\"}[1m])) by (pod)",
     "legendFormat": "Missing ICMP Echo-Reply"
    }
   ]
  },
  { "title": "Network Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Denies by Reason",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"Policy denied (L3)\"}[1m])) by (pod, reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Denied Packets by Protocol",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{reason=\"Policy denied (L3)\"}[1m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top 10 Source Pods with Denied Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"Policy denied (L3)\"}[1m])) by (pod, source))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Top 10 Destination Pods with Denied Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_drop_total{reason=\"Policy denied (L3)\"}[1m])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total[1m])) by (pod, method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_http_responses_total[1m])) by (pod, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request/Response Latency (p50)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(hubble_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Request/Response Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(hubble_http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Protocol Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total[5m])) by (pod, protocol)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "DNS Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS responses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\"}[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "Missing DNS Responses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_queries_total[1m])) by (pod, qtypes) - sum(rate(hubble_dns_responses_total[1m])) by (pod, qtypes)",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "DNS Response Record Type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_response_types_total[1m])) by (pod, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "DNS Response IPs Returned",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode=\"No Error\"}[1m])) by (pod,ips_returned)",
     "legendFormat": "{{ips_returned}}"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{rcode!=\"No Error\"}[1m])) by (pod, qtypes, rcode)",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Pods with DNS errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(rate(hubble_dns_responses_total{rcode!=\"No Error\"}[1m])) by (pod, destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top 10 DNS Queries per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(hubble_dns_queries_total[10m])*60) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  }
 ]
}